# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: arigato_wordpress
  pool: 5
  username: cs
  password:
  socket: /var/run/mysqld/mysqld.sock
